### ISSUE TITLE
i think you wrong 

### ISSUE THREAD

**Issue by JustPandaEver** [yanpaing007/binance_moonbix#1]
print("Game started successfully")
                    await get_user_info("2056", access_token)
                    data = await response.json()
                    
                    json_payload = json.dumps(data)

                    # Encode the JSON string to a base64 string
                    encoded_payload = base64.b64encode(json_payload.encode()).decode()
                    
encoded_payload i think this payload are wrong sir,because got 0 point and submit status is false

**Comment by JustPandaEver** [comment]
{'code': '116003', 'message': 'User: ....., complete game failed, input: MiniAppActivityInput(userId=....., nickName=..... , socialType=telegram, resourceId=2056, log=120, payload=eyJjb2RlIjogIjAwMDAwMCIsICJtZXNzYWdlIjogbnVsbCwgIm1lc3NhZ2VEZXRhaWwiOiBudWxsLCAiZGF0YSI6IHsiZ2FtZVRhZyI6ICI3YTI5YjkxODliZTY4NjE4N2ZiNzM3N2EzZGYxOGY4NiIsICJzcGVjaWFsUmV3YXJkSWQiOiBudWxsLCAiY3J5cHRvTWluZXJDb25maWciOiB7ImdhbWVEdXJhdGlvbiI6IG51bGwsICJob29rU3dpcGVTcGVlZCI6IDMwMCwgImZpbmFsSG9va1N3aXBlU3BlZWQiOiA1MDAsICJpdGVtU2V0dGluZ0xpc3QiOiBbeyJ0eXBlIjogIkJPTlVTIiwgInNwZWVkIjogODAsICJzaXplIjogNjAsICJxdWFudGl0eSI6IDEsICJyZXdhcmRWYWx1ZUxpc3QiOiBbNjBdfSwgeyJ0eXBlIjogIlJFV0FSRCIsICJzcGVlZCI6IDEwMCwgInNpemUiOiA3MCwgInF1YW50aXR5IjogMiwgInJld2FyZFZhbHVlTGlzdCI6IFs1MCwgNTBdfSwgeyJ0eXBlIjogIlRSQVAiLCAic3BlZWQiOiAxMDAsICJzaXplIjogNTAsICJxdWFudGl0eSI6IDEsICJyZXdhcmRWYWx1ZUxpc3QiOiBbLTIwXX0sIHsidHlwZSI6ICJSRVdBUkQiLCAic3BlZWQiOiAyMDAsICJzaXplIjogMzAsICJxdWFudGl0eSI6IDUsICJyZXdhcmRWYWx1ZUxpc3QiOiBbMTAsIDEwLCAxMCwgMTAsIDEwXX0sIHsidHlwZSI6ICJUUkFQIiwgInNwZWVkIjogMTUwLCAic2l6ZSI6IDMwLCAicXVhbnRpdHkiOiAyLCAicmV3YXJkVmFsdWVMaXN0IjogWy0xMCwgLTEwXX0sIHsidHlwZSI6ICJSRVdBUkQiLCAic3BlZWQiOiAxNTAsICJzaXplIjogNTAsICJxdWFudGl0eSI6IDMsICJyZXdhcmRWYWx1ZUxpc3QiOiBbMjUsIDI1LCAyNV19XX19LCAic3VjY2VzcyI6IHRydWV9, userIp=null).', 'messageDetail': None, 'data': None, 'success': False}
remaining Attempts: 3

**Comment by arifintajul4** [comment]
same problem, 0 point in game
<img width="414" alt="Screenshot 2024-09-21 at 16 19 53" src="https://github.com/user-attachments/assets/b48773ae-d771-4f93-8820-1786708e7fbf">

**Comment by yanpaing007** [comment]
Yes,payload is wrong ,I already warn this in ReadME.md , I am trying to find a way to make this work,This payload just generate random string which is kind of bs and I updated the code to disable game play
